### ISSUE TITLE
[Enhancement] - Credits can be enhanced

### ISSUE THREAD

**Issue by ayushichoudhary-19** [ayushsarode/CardConnect-HacktoberfestEdition23#12]
Screenshot:
![image](https://github.com/ayushsarode/CardConnect-HacktoberfestEdition23/assets/73214455/11401c3b-29cf-4c7c-9470-73df6e0b7478)

Issue:
1. The name should begin with a capital 'A'.
2. I suggest we use the Typed.js library to create a typewriter effect for the entire credit text, making it appear as if it's being written in real-time. This will make the page more interactive
 **Reference:** https://mattboldt.com/demos/typed-js/
 
I would like to work on this issue if it aligns with the goals of the project.

**Comment by ayushsarode** [comment]
Sure you can give it a try! 👍

**Comment by ayushichoudhary-19** [comment]
Please review https://github.com/ayushsarode/CardConnect-HacktoberfestEdition23/pull/13#issuecomment-1741832658

**Comment by ayushsarode** [comment]
> Please review [#13 (comment)](https://github.com/ayushsarode/CardConnect-HacktoberfestEdition23/pull/13#issuecomment-1741832658)
> 
> @ayushsarode

Please you have to check what's going wrong with your PR, you copied wrong code, you should resolve it and then I'll merge it!
Thank you!
