### ISSUE TITLE
add Responsiveness to website

### ISSUE THREAD

**Issue by ayushsarode** [ayushsarode/CardConnect-HacktoberfestEdition23#2]
We need to improve the responsiveness of our website for mobile and tablet version.

**Comment by avtarsingh99** [comment]
I would like to contribute to this issue.

**Comment by ayushsarode** [comment]
> I would like to contribute to this issue.

Sure, Go ahead!

**Comment by Basavarajakjbasuu** [comment]
I will work on this issue could you pleas assign to me

**Comment by ayushsarode** [comment]
> I will work on this issue could you pleas assign to me

Sure!

Also you can contribute via creating profile-card on this repo.
Check out [contributing.md](https://github.com/ayushsarode/HacktoberFest2023-Profile-Card/blob/main/Contributing.md)

**Comment by Basavarajakjbasuu** [comment]
Can I raise PR on October 1st so tht our contribution count hectobet fest

**Comment by ayushsarode** [comment]
> Can I raise PR on October 1st so tht our contribution count hectobet fest

Indeed! Even if you do it before, I'll make sure to merge it after 1st Oct.
