### ISSUE TITLE
Improvement of the Border radius and a footer enhancement

### ISSUE THREAD

**Issue by Kaniz-Fatma** [ayushsarode/CardConnect-HacktoberfestEdition23#4]
The cards border radius is appearing rounded from only one side and does not looks so good. It would be good if the card appears properly. I would like to work on that issue and a little bit improvement can be made in the footer also. It would be appreciated if you assign this issue to me.

**Comment by ayushsarode** [comment]
> The cards border radius is appearing rounded from only one side and does not looks so good. It would be good if the card appears properly. I would like to work on that issue and a little bit improvement can be made in the footer also. It would be appreciated if you assign this issue to me.

No need to change card design. 
If you can design nice footer than yes, go head
