### ISSUE TITLE
Improve the Title

### ISSUE THREAD

**Issue by ayushsarode** [ayushsarode/CardConnect-HacktoberfestEdition23#5]
Make the title more appealing to the audience.
Instead of "Profile Card" use "Profile Card Hacktoberfest Edition"

**Comment by debuuuu007** [comment]
I would be glad if you assign me this issue. I want to work on both the textual and design of that H1 tag.

**Comment by abhaygzb15** [comment]
@ayushsarode Hey!! I would be grateful if you could assign this  issue to me.

**Comment by ayushsarode** [comment]
Sure, note that the design should be appealing!

**Comment by ayushsarode** [comment]
> I would be glad if you assign me this issue. I want to work on both the textual and design of that H1 tag.

Go ahead!
