### ISSUE TITLE
THIS REPOSITORY IS EXCLUDED FROM HACKTOBERFEST2023 . DON'T CONTRIBUTE IN THIS REPO :(

### ISSUE THREAD

**Issue by Ankit9126** [ayushsarode/CardConnect-HacktoberfestEdition23#59]

**Comment by ayushsarode** [comment]
Regarding your concern about our repository's exclusion from Hacktoberfest 2023, I want to clarify our stance. While we're not officially participating in the event, our repository is open to contributions. We've explicitly stated in our README that contributions won't count towards Hacktoberfest swag.

Our focus is on welcoming new contributors and fostering a learning environment. We believe in the intrinsic value of open source collaboration beyond swag rewards. We urge you to embrace this philosophy and contribute for the sake of improving your skills and helping the community.

Please understand our perspective and join us in the spirit of knowledge sharing and growth. Should you have questions or need assistance, feel free to reach out. We appreciate your interest and look forward to your meaningful contributions.


![Screenshot 2023-10-03 201249](https://github.com/ayushsarode/CardConnect-HacktoberfestEdition23/assets/72145248/6dac4033-5476-4786-9924-bf0af3abe688)

**Comment by naomi-lgbt** [comment]
You should remove the topic, then. :3

**Comment by ayushsarode** [comment]
> You should remove the topic, then. :3

Sure!
