### ISSUE TITLE
Create a Scroll Back To Top Button

### ISSUE THREAD

**Issue by ayushsarode** [ayushsarode/CardConnect-HacktoberfestEdition23#67]
As the web app will get longer and longer, create a _**scroll back to top button**_ so that it'll be easy for user to go on the top of the Page

**Comment by rahulpandey70** [comment]
Can I work on this issue?

**Comment by kshitizvardhan** [comment]
Hi Please assign me the issue, i can add the scroll back to top button
Thank You

**Comment by ayushsarode** [comment]
Sure! Go Ahead

**Comment by mdfaizalam555** [comment]
kindly assign me this issue @ayushsarode
